# monitor.ps1
# Auto-generated by USB Monitor Config Generator
# Generated at: 2026-07-11T08:25:29.677Z

$serverUrl = "https://localhost:8443/api/usb-event"
$apiKey = "your-secret-api-key-here"
$computerId = $env:COMPUTERNAME
$pollSeconds = 3

# Auto-unblock files in this folder (in case downloaded from browser / copied from network share)
Get-ChildItem $PSScriptRoot -Recurse -ErrorAction SilentlyContinue | Unblock-File -ErrorAction SilentlyContinue

[System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $true }

function Get-USBDisks {
    Get-Disk | Where-Object { $_.BusType -eq "USB" } | Select-Object Number, FriendlyName, SerialNumber
}

$previousDisks = Get-USBDisks
Write-Host "USB monitoring started for [$computerId]. Detected $($previousDisks.Count) USB device(s):"
$previousDisks | ForEach-Object { Write-Host "  - $($_.FriendlyName) ($($_.SerialNumber))" }

while ($true) {
    Start-Sleep -Seconds $pollSeconds
    $currentDisks = Get-USBDisks

    $removed = $previousDisks | Where-Object {
        $sn = $_.SerialNumber
        -not ($currentDisks | Where-Object { $_.SerialNumber -eq $sn })
    }

    $added = $currentDisks | Where-Object {
        $sn = $_.SerialNumber
        -not ($previousDisks | Where-Object { $_.SerialNumber -eq $sn })
    }

    foreach ($disk in $added) {
        Write-Host "Device connected: $($disk.FriendlyName) - $($disk.SerialNumber)"
        $payload = @{
            computer  = $computerId
            model     = $disk.FriendlyName
            serial    = $disk.SerialNumber
            timestamp = (Get-Date).ToString("o")
            event     = "connected"
        } | ConvertTo-Json

        try {
            Invoke-RestMethod -Uri $serverUrl `
                -Method Post -Body $payload -ContentType "application/json" `
                -Headers @{ "Authorization" = "Bearer $apiKey" } -TimeoutSec 5

            Write-Host "Reported: $($disk.FriendlyName) - $($disk.SerialNumber)"
        } catch {
            Write-Host "Report failed: $_"
            $payload | Out-File -Append (Join-Path $PSScriptRoot "failed-events.log")
        }
    }

    foreach ($disk in $removed) {

        $modulePath = Join-Path $PSScriptRoot "Modules\BurntToast\BurntToast.psd1"
        if (Test-Path $modulePath) {
            Import-Module $modulePath -Force -ErrorAction SilentlyContinue
        }
        if (Get-Command New-BurntToastNotification -ErrorAction SilentlyContinue) {
            New-BurntToastNotification -Text "USB Device Removed", "$($disk.FriendlyName) (Serial: $($disk.SerialNumber))" -Sound Alarm
        } else {
            Write-Host "[Warning] BurntToast module not found, skipping toast notification."
        }

        $payload = @{
            computer  = $computerId
            model     = $disk.FriendlyName
            serial    = $disk.SerialNumber
            timestamp = (Get-Date).ToString("o")
            event     = "removed"
        } | ConvertTo-Json

        try {
            Invoke-RestMethod -Uri $serverUrl `
                -Method Post -Body $payload -ContentType "application/json" `
                -Headers @{ "Authorization" = "Bearer $apiKey" } -TimeoutSec 5

            Write-Host "Reported: $($disk.FriendlyName) - $($disk.SerialNumber)"
        } catch {
            Write-Host "Report failed: $_"
            $payload | Out-File -Append (Join-Path $PSScriptRoot "failed-events.log")
        }
    }

    $previousDisks = $currentDisks
}
